// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs3xCfuRXuV119Wexo-2fFbEeV8lY3LIY',
    appId: '1:484107930819:web:d9def6ad6c8257947c2676',
    messagingSenderId: '484107930819',
    projectId: 'flutter-best-heating',
    authDomain: 'flutter-best-heating.firebaseapp.com',
    storageBucket: 'flutter-best-heating.appspot.com',
    measurementId: 'G-XPZ2CNE32V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNegenQgrKRJLEV6pSV_E0kUKIqU6Sv8',
    appId: '1:484107930819:android:dbe130ef088d23047c2676',
    messagingSenderId: '484107930819',
    projectId: 'flutter-best-heating',
    storageBucket: 'flutter-best-heating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9aVkApmWPDuzDsyhNoeFGAukttx-Bwsg',
    appId: '1:484107930819:ios:aff555de65ec1bfb7c2676',
    messagingSenderId: '484107930819',
    projectId: 'flutter-best-heating',
    storageBucket: 'flutter-best-heating.appspot.com',
    iosClientId: '484107930819-p07lrd7blrqbgro3ioplqi00bo22mnom.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestHeating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9aVkApmWPDuzDsyhNoeFGAukttx-Bwsg',
    appId: '1:484107930819:ios:aff555de65ec1bfb7c2676',
    messagingSenderId: '484107930819',
    projectId: 'flutter-best-heating',
    storageBucket: 'flutter-best-heating.appspot.com',
    iosClientId: '484107930819-p07lrd7blrqbgro3ioplqi00bo22mnom.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestHeating',
  );
}
